#!/bin/sh

BOARD="$(cat /tmp/sysinfo/board_name 2>/dev/null || true)"
[ "$BOARD" = "airpi,ap3000m" ] || exit 0

LOG="/tmp/airpi-oldfw-network-defaults.log"
exec >>"$LOG" 2>&1

echo "[Airpi] applying safe old firmware compatible defaults"
date

# IMPORTANT:
# Do not create named br-lan UCI section.
# Do not delete bridge ports.
# Let chasey board.d/config_generate create br-lan = eth0.
# Only apply old project parameters.

uci set system.@system[0].hostname='Airpi' 2>/dev/null || true

uci -q batch <<'EOC'
set network.lan=interface
set network.lan.device='br-lan'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.1.1'
set network.lan.netmask='255.255.255.0'
set network.lan.ip6assign='60'

set network.wan=interface
set network.wan.device='eth1'
set network.wan.proto='dhcp'

set network.wan6=interface
set network.wan6.device='eth1'
set network.wan6.proto='dhcpv6'

network.wwan=interface
network.wwan.proto='static'
network.wwan.device='wwan0'
network.wwan.multipath='on'
network.wwan.ip6assign='64'

set dhcp.lan=dhcp
set dhcp.lan.interface='lan'
set dhcp.lan.start='100'
set dhcp.lan.limit='150'
set dhcp.lan.leasetime='12h'
set dhcp.lan.dhcpv4='server'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra='server'
set dhcp.lan.ra_slaac='1'
set dhcp.lan.max_preferred_lifetime='2700'
set dhcp.lan.max_valid_lifetime='5400'
delete dhcp.lan.ignore
EOC

# Firewall old project compatible layout.
if ! uci -q show firewall.@zone[0] >/dev/null 2>&1; then
  uci -q add firewall zone >/dev/null
fi

if ! uci -q show firewall.@zone[1] >/dev/null 2>&1; then
  uci -q add firewall zone >/dev/null
fi

uci -q batch <<'EOC'
set firewall.@zone[0].name='lan'
set firewall.@zone[0].network='lan'
set firewall.@zone[0].input='ACCEPT'
set firewall.@zone[0].output='ACCEPT'
set firewall.@zone[0].forward='ACCEPT'

set firewall.@zone[1].name='wan'
delete firewall.@zone[1].network
add_list firewall.@zone[1].network='wan'
add_list firewall.@zone[1].network='wan6'
set firewall.@zone[1].input='REJECT'
set firewall.@zone[1].output='ACCEPT'
set firewall.@zone[1].forward='REJECT'
set firewall.@zone[1].masq='1'
set firewall.@zone[1].mtu_fix='1'
EOC

if ! uci -q show firewall | grep -q "src='lan'.*dest='wan'"; then
  uci -q add firewall forwarding >/dev/null
  uci -q set firewall.@forwarding[-1].src='lan'
  uci -q set firewall.@forwarding[-1].dest='wan'
fi

for svc in dnsmasq firewall network eqos turboacc ttyd; do
  if [ -x "/etc/init.d/$svc" ]; then
    /etc/init.d/"$svc" enable >/dev/null 2>&1 || true
  fi
done

uci commit system
uci commit network
uci commit dhcp
uci commit firewall

echo "[Airpi] final network:"
uci show network | grep -E 'br-lan|eth0|eth1|lan|wan|wwan' || true

rm -f /etc/uci-defaults/99-airpi-oldfw-network
exit 0
